## file
file:
  path:
    ## openai api key
    gpt3ApiKey: c2stSjZqU3FMbUtrWkZnMnhjd29WSW5UM0JsYmtGSkhuN2hHNE1sd2FWaVduRFdOMklm

## job config
job:
  config:
    bili:
      - bots: "1730814323"
        groups: "793900042"
        uids: "3780145"
        # 0 关注 1 番剧
        type: 0